window.PRODUCTS=[
  {
    "id": "dress_001",
    "category": "dress",
    "categoryName": "Платья",
    "name": "Платье «Лилия»",
    "price": 1990,
    "oldPrice": 2490,
    "rating": 4.6,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Платье"
  },
  {
    "id": "dress_002",
    "category": "dress",
    "categoryName": "Платья",
    "name": "Платье «Аврора»",
    "price": 2790,
    "oldPrice": 3290,
    "rating": 4.4,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Платье"
  },
  {
    "id": "dress_003",
    "category": "dress",
    "categoryName": "Платья",
    "name": "Платье «Эмилия»",
    "price": 3190,
    "oldPrice": 3890,
    "rating": 4.9,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Платье"
  },
  {
    "id": "dress_004",
    "category": "dress",
    "categoryName": "Платья",
    "name": "Платье «Сакура»",
    "price": 2790,
    "oldPrice": 3490,
    "rating": 4.5,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Платье"
  },
  {
    "id": "dress_005",
    "category": "dress",
    "categoryName": "Платья",
    "name": "Платье «Виктория»",
    "price": 1990,
    "oldPrice": 2490,
    "rating": 4.2,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Платье"
  },
  {
    "id": "dress_006",
    "category": "dress",
    "categoryName": "Платья",
    "name": "Платье «Мелисса»",
    "price": 5490,
    "oldPrice": 6190,
    "rating": 4.2,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Платье"
  },
  {
    "id": "dress_007",
    "category": "dress",
    "categoryName": "Платья",
    "name": "Платье «Камелия»",
    "price": 2490,
    "oldPrice": 3490,
    "rating": 4.5,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Платье"
  },
  {
    "id": "dress_008",
    "category": "dress",
    "categoryName": "Платья",
    "name": "Платье «Элина»",
    "price": 3190,
    "oldPrice": 3690,
    "rating": 4.9,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Платье"
  },
  {
    "id": "jeans_009",
    "category": "jeans",
    "categoryName": "Джинсы",
    "name": "Джинсы «Classic Fit»",
    "price": 3590,
    "oldPrice": 4590,
    "rating": 4.4,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Джинсы"
  },
  {
    "id": "jeans_010",
    "category": "jeans",
    "categoryName": "Джинсы",
    "name": "Джинсы «Mom Fit»",
    "price": 4490,
    "oldPrice": 5490,
    "rating": 4.7,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Джинсы"
  },
  {
    "id": "jeans_011",
    "category": "jeans",
    "categoryName": "Джинсы",
    "name": "Джинсы «Straight»",
    "price": 4990,
    "oldPrice": 5490,
    "rating": 4.4,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Джинсы"
  },
  {
    "id": "jeans_012",
    "category": "jeans",
    "categoryName": "Джинсы",
    "name": "Джинсы «Wide Leg»",
    "price": 3190,
    "oldPrice": 3690,
    "rating": 4.7,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Джинсы"
  },
  {
    "id": "jeans_013",
    "category": "jeans",
    "categoryName": "Джинсы",
    "name": "Джинсы «Slim»",
    "price": 2490,
    "oldPrice": 2990,
    "rating": 4.6,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Джинсы"
  },
  {
    "id": "jeans_014",
    "category": "jeans",
    "categoryName": "Джинсы",
    "name": "Джинсы «Vintage»",
    "price": 5490,
    "oldPrice": 6490,
    "rating": 4.5,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Джинсы"
  },
  {
    "id": "jeans_015",
    "category": "jeans",
    "categoryName": "Джинсы",
    "name": "Джинсы «Urban»",
    "price": 1990,
    "oldPrice": 2690,
    "rating": 4.2,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Джинсы"
  },
  {
    "id": "jeans_016",
    "category": "jeans",
    "categoryName": "Джинсы",
    "name": "Джинсы «Relax»",
    "price": 5490,
    "oldPrice": 6190,
    "rating": 4.6,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Джинсы"
  },
  {
    "id": "sundress_017",
    "category": "sundress",
    "categoryName": "Сарафаны",
    "name": "Сарафан «Лето»",
    "price": 3590,
    "oldPrice": 4290,
    "rating": 4.3,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Сарафан"
  },
  {
    "id": "sundress_018",
    "category": "sundress",
    "categoryName": "Сарафаны",
    "name": "Сарафан «Лаванда»",
    "price": 5490,
    "oldPrice": 6490,
    "rating": 4.3,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Сарафан"
  },
  {
    "id": "sundress_019",
    "category": "sundress",
    "categoryName": "Сарафаны",
    "name": "Сарафан «Марина»",
    "price": 5490,
    "oldPrice": 6490,
    "rating": 4.7,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Сарафан"
  },
  {
    "id": "sundress_020",
    "category": "sundress",
    "categoryName": "Сарафаны",
    "name": "Сарафан «Флора»",
    "price": 5490,
    "oldPrice": 6490,
    "rating": 4.3,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Сарафан"
  },
  {
    "id": "sundress_021",
    "category": "sundress",
    "categoryName": "Сарафаны",
    "name": "Сарафан «Бриз»",
    "price": 4990,
    "oldPrice": 5490,
    "rating": 4.3,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Сарафан"
  },
  {
    "id": "sundress_022",
    "category": "sundress",
    "categoryName": "Сарафаны",
    "name": "Сарафан «Солнце»",
    "price": 2490,
    "oldPrice": 3490,
    "rating": 4.9,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Сарафан"
  },
  {
    "id": "skirts_023",
    "category": "skirts",
    "categoryName": "Юбки",
    "name": "Юбка «Амелия»",
    "price": 2790,
    "oldPrice": 3490,
    "rating": 4.6,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Юбка"
  },
  {
    "id": "skirts_024",
    "category": "skirts",
    "categoryName": "Юбки",
    "name": "Юбка «Луна»",
    "price": 2790,
    "oldPrice": 3490,
    "rating": 4.8,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Юбка"
  },
  {
    "id": "skirts_025",
    "category": "skirts",
    "categoryName": "Юбки",
    "name": "Юбка «Эстер»",
    "price": 5490,
    "oldPrice": 5990,
    "rating": 4.7,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Юбка"
  },
  {
    "id": "skirts_026",
    "category": "skirts",
    "categoryName": "Юбки",
    "name": "Юбка «Миди»",
    "price": 1990,
    "oldPrice": 2990,
    "rating": 4.7,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Юбка"
  },
  {
    "id": "skirts_027",
    "category": "skirts",
    "categoryName": "Юбки",
    "name": "Юбка «Плиссе»",
    "price": 3190,
    "oldPrice": 4190,
    "rating": 4.5,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Юбка"
  },
  {
    "id": "skirts_028",
    "category": "skirts",
    "categoryName": "Юбки",
    "name": "Юбка «Мини»",
    "price": 5490,
    "oldPrice": 6190,
    "rating": 4.5,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Юбка"
  },
  {
    "id": "tops_029",
    "category": "tops",
    "categoryName": "Топы и майки",
    "name": "Топ «Весна»",
    "price": 3990,
    "oldPrice": 4990,
    "rating": 5.0,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Топ"
  },
  {
    "id": "tops_030",
    "category": "tops",
    "categoryName": "Топы и майки",
    "name": "Топ «Basic»",
    "price": 2490,
    "oldPrice": 3490,
    "rating": 4.3,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Топ"
  },
  {
    "id": "tops_031",
    "category": "tops",
    "categoryName": "Топы и майки",
    "name": "Топ «Soft»",
    "price": 3590,
    "oldPrice": 4590,
    "rating": 4.3,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Топ"
  },
  {
    "id": "tops_032",
    "category": "tops",
    "categoryName": "Топы и майки",
    "name": "Топ «Cloud»",
    "price": 3190,
    "oldPrice": 3890,
    "rating": 4.3,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Топ"
  },
  {
    "id": "tops_033",
    "category": "tops",
    "categoryName": "Топы и майки",
    "name": "Топ «Silk»",
    "price": 4490,
    "oldPrice": 5190,
    "rating": 4.8,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Топ"
  },
  {
    "id": "tops_034",
    "category": "tops",
    "categoryName": "Топы и майки",
    "name": "Топ «Summer»",
    "price": 4490,
    "oldPrice": 5490,
    "rating": 4.6,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Топ"
  },
  {
    "id": "blouses_035",
    "category": "blouses",
    "categoryName": "Блузки",
    "name": "Блузка «Милан»",
    "price": 1990,
    "oldPrice": 2490,
    "rating": 4.6,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Блузка"
  },
  {
    "id": "blouses_036",
    "category": "blouses",
    "categoryName": "Блузки",
    "name": "Блузка «Оливия»",
    "price": 3990,
    "oldPrice": 4690,
    "rating": 4.6,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Блузка"
  },
  {
    "id": "blouses_037",
    "category": "blouses",
    "categoryName": "Блузки",
    "name": "Блузка «Линда»",
    "price": 5490,
    "oldPrice": 6490,
    "rating": 4.5,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Блузка"
  },
  {
    "id": "blouses_038",
    "category": "blouses",
    "categoryName": "Блузки",
    "name": "Блузка «Grace»",
    "price": 2490,
    "oldPrice": 3190,
    "rating": 4.6,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Блузка"
  },
  {
    "id": "blouses_039",
    "category": "blouses",
    "categoryName": "Блузки",
    "name": "Блузка «Pearl»",
    "price": 2790,
    "oldPrice": 3490,
    "rating": 4.3,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Блузка"
  },
  {
    "id": "blouses_040",
    "category": "blouses",
    "categoryName": "Блузки",
    "name": "Блузка «Classic»",
    "price": 2790,
    "oldPrice": 3290,
    "rating": 4.4,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Блузка"
  },
  {
    "id": "pants_041",
    "category": "pants",
    "categoryName": "Брюки",
    "name": "Брюки «Palazzo»",
    "price": 2790,
    "oldPrice": 3290,
    "rating": 4.5,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Брюки"
  },
  {
    "id": "pants_042",
    "category": "pants",
    "categoryName": "Брюки",
    "name": "Брюки «Office»",
    "price": 2790,
    "oldPrice": 3290,
    "rating": 4.4,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Брюки"
  },
  {
    "id": "pants_043",
    "category": "pants",
    "categoryName": "Брюки",
    "name": "Брюки «Smart»",
    "price": 3590,
    "oldPrice": 4590,
    "rating": 4.4,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Брюки"
  },
  {
    "id": "pants_044",
    "category": "pants",
    "categoryName": "Брюки",
    "name": "Брюки «Relax»",
    "price": 4990,
    "oldPrice": 5490,
    "rating": 4.9,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Брюки"
  },
  {
    "id": "pants_045",
    "category": "pants",
    "categoryName": "Брюки",
    "name": "Брюки «Weekend»",
    "price": 3190,
    "oldPrice": 3690,
    "rating": 4.9,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Брюки"
  },
  {
    "id": "pants_046",
    "category": "pants",
    "categoryName": "Брюки",
    "name": "Брюки «City»",
    "price": 4490,
    "oldPrice": 5490,
    "rating": 4.4,
    "isNew": true,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Брюки"
  },
  {
    "id": "lingerie_047",
    "category": "lingerie",
    "categoryName": "Нижнее белье",
    "name": "Комплект «Rose»",
    "price": 3590,
    "oldPrice": 4090,
    "rating": 4.7,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Комплект"
  },
  {
    "id": "lingerie_048",
    "category": "lingerie",
    "categoryName": "Нижнее белье",
    "name": "Комплект «Velvet»",
    "price": 3990,
    "oldPrice": 4490,
    "rating": 4.3,
    "isNew": false,
    "isSale": true,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Комплект"
  },
  {
    "id": "lingerie_049",
    "category": "lingerie",
    "categoryName": "Нижнее белье",
    "name": "Комплект «Soft»",
    "price": 3590,
    "oldPrice": 4290,
    "rating": 4.6,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Комплект"
  },
  {
    "id": "lingerie_050",
    "category": "lingerie",
    "categoryName": "Нижнее белье",
    "name": "Комплект «Elegant»",
    "price": 3590,
    "oldPrice": 4590,
    "rating": 4.6,
    "isNew": false,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Комплект"
  },
  {
    "id": "lingerie_051",
    "category": "lingerie",
    "categoryName": "Нижнее белье",
    "name": "Комплект «Classic»",
    "price": 4490,
    "oldPrice": 4990,
    "rating": 4.6,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Комплект"
  },
  {
    "id": "lingerie_052",
    "category": "lingerie",
    "categoryName": "Нижнее белье",
    "name": "Комплект «Comfort»",
    "price": 5490,
    "oldPrice": 6190,
    "rating": 4.9,
    "isNew": true,
    "isSale": false,
    "image": "https://placehold.co/600x800/FDE8F1/555?text=Комплект"
  }
];