
window.Ecommerce={
 viewHome(){track("view_home");},
 viewItemList(category){
   track("view_item_list",{item_list_name:category});
 },
 viewItem(product){
   track("view_item",{
     ecommerce:{
       currency:"RUB",
       value:product.price,
       items:[{
         item_id:product.id,
         item_name:product.name,
         item_category:product.categoryName,
         price:product.price
       }]
     }
   });
 },
 addToCart(product){
   track("add_to_cart",{
     ecommerce:{
       currency:"RUB",
       value:product.price,
       items:[{
         item_id:product.id,
         item_name:product.name,
         item_category:product.categoryName,
         quantity:1,
         price:product.price
       }]
     }
   });
 },
 viewCart(items){
   track("view_cart",{
     ecommerce:{currency:"RUB",items}
   });
 },
 beginCheckout(total){
   track("begin_checkout",{
     ecommerce:{currency:"RUB",value:total}
   });
 },
 purchase(total){
   track("purchase",{
     ecommerce:{
       transaction_id:"ORDER-"+Date.now(),
       currency:"RUB",
       value:total
     }
   });
 },
 search(term){
   track("search",{search_term:term});
 }
};
